POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: Bearer hi

{
    "title": "3nd testing",
    "author": "Vuong",
    "url": "www.hi.com",
    "likes": 0,
    "userId": "67c2c5391ee1259a4607f03c"
}